#
# Simple Makefile that compiles all .c and .s files in the same folder
#

# If you move this project you can change the directory 
# to match your GBDK root directory (ex: GBDK_HOME = "C:/GBDK/"
GBDK_HOME = "/opt/gbdk/"

LCC = $(GBDK_HOME)bin/lcc
PNG2MTSPR = $(GBDK_HOME)bin/png2mtspr

# You can uncomment the line below to turn on debug output
#LCC = $(LCC) -debug

# You can set the name of the .gb ROM file here
PROJECTNAME    = Cuphead

BINS	    = $(PROJECTNAME).gb

# Add entries here to have them converted into metasprites
PNGSOURCES   = sprite_player_idle.png sprite_player_fire.png
PNG_CSOURCES = $(PNGSOURCES:%.png=%.c)
PNG_CHEADERS = $(PNGSOURCES:%.png=%.h)


# List of all C source files except those generated by png2mtspr
CSOURCES    = $(filter-out $(PNGSOURCES:%.png=%.c), $(wildcard *.c))
ASMSOURCES := $(wildcard *.s)

all:	$(BINS)

make.bat: Makefile
	@echo "REM Automatically generated from Makefile" > make.bat
	@make -sn | sed y/\\//\\\\/ | grep -v make >> make.bat

# Use png2mtspr to convert the png into C formatted metasprite data
# -sh 48   : Sets sprite height to 48 (width remains automatic)
# -spr8x16 : Use 8x16 hardware sprites
# -c ...   : Set C output file
%.c:	%.png
	$(PNG2MTSPR) $< -sh 16 -spr8x8 -c $@ 

# Compile and link all source files in a single call to LCC
$(BINS):	$(CSOURCES) $(ADMSOURCES) $(PNG_CSOURCES)
	$(LCC) -o $@ $(CSOURCES) $(ADMSOURCES) $(PNG_CSOURCES)

clean:
	rm -f *.o *.lst *.map *.gb *.ihx *.sym *.cdb *.adb *.asm $(PNG_CHEADERS) $(PNG_CSOURCES)

