//AUTOGENERATED FILE FROM png2mtspr
#define sprite_player_fire_TILE_H 8
#define sprite_player_fire_WIDTH 16
#define sprite_player_fire_HEIGHT 16
#define sprite_player_fire_PIVOT_X 8
#define sprite_player_fire_PIVOT_Y 8

extern const UINT8 sprite_player_fire_data[96];
extern const metasprite_t* const sprite_player_fire_metasprites[2];
