//AUTOGENERATED FILE FROM png2mtspr
#define sprite_player_idle_TILE_H 8
#define sprite_player_idle_WIDTH 16
#define sprite_player_idle_HEIGHT 16
#define sprite_player_idle_PIVOT_X 8
#define sprite_player_idle_PIVOT_Y 8

extern const UINT8 sprite_player_idle_data[192];
extern const metasprite_t* const sprite_player_idle_metasprites[4];
