//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sprite_player_jump_H
#define METASPRITE_sprite_player_jump_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sprite_player_jump_TILE_ORIGIN 0
#define sprite_player_jump_TILE_W 8
#define sprite_player_jump_TILE_H 8
#define sprite_player_jump_WIDTH 16
#define sprite_player_jump_HEIGHT 16
#define sprite_player_jump_TILE_COUNT 32
#define sprite_player_jump_PALETTE_COUNT 1
#define sprite_player_jump_COLORS_PER_PALETTE 4
#define sprite_player_jump_TOTAL_COLORS 4
#define sprite_player_jump_PIVOT_X 8
#define sprite_player_jump_PIVOT_Y 8
#define sprite_player_jump_PIVOT_W 16
#define sprite_player_jump_PIVOT_H 16

BANKREF_EXTERN(sprite_player_jump)

extern const palette_color_t sprite_player_jump_palettes[4];
extern const uint8_t sprite_player_jump_tiles[512];

extern const metasprite_t* const sprite_player_jump_metasprites[8];

#endif
