//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sprite_player_idle_H
#define METASPRITE_sprite_player_idle_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sprite_player_idle_TILE_ORIGIN 0
#define sprite_player_idle_TILE_W 8
#define sprite_player_idle_TILE_H 8
#define sprite_player_idle_WIDTH 16
#define sprite_player_idle_HEIGHT 16
#define sprite_player_idle_TILE_COUNT 12
#define sprite_player_idle_PALETTE_COUNT 1
#define sprite_player_idle_COLORS_PER_PALETTE 4
#define sprite_player_idle_TOTAL_COLORS 4
#define sprite_player_idle_PIVOT_X 8
#define sprite_player_idle_PIVOT_Y 8
#define sprite_player_idle_PIVOT_W 16
#define sprite_player_idle_PIVOT_H 16

BANKREF_EXTERN(sprite_player_idle)

extern const palette_color_t sprite_player_idle_palettes[4];
extern const uint8_t sprite_player_idle_tiles[192];

extern const metasprite_t* const sprite_player_idle_metasprites[4];

#endif
