//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_sprite_player_fire_H
#define METASPRITE_sprite_player_fire_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define sprite_player_fire_TILE_ORIGIN 0
#define sprite_player_fire_TILE_W 8
#define sprite_player_fire_TILE_H 8
#define sprite_player_fire_WIDTH 16
#define sprite_player_fire_HEIGHT 16
#define sprite_player_fire_TILE_COUNT 6
#define sprite_player_fire_PALETTE_COUNT 1
#define sprite_player_fire_COLORS_PER_PALETTE 4
#define sprite_player_fire_TOTAL_COLORS 4
#define sprite_player_fire_PIVOT_X 8
#define sprite_player_fire_PIVOT_Y 8
#define sprite_player_fire_PIVOT_W 16
#define sprite_player_fire_PIVOT_H 16

BANKREF_EXTERN(sprite_player_fire)

extern const palette_color_t sprite_player_fire_palettes[4];
extern const uint8_t sprite_player_fire_tiles[96];

extern const metasprite_t* const sprite_player_fire_metasprites[2];

#endif
