#include "sprite_player_bullet.h"
/*

 SPRITE_PLAYER_BULLET.C

 Tile Source File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 0

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

/* Start of tile array. */
const uint8_t sprite_player_bullet_tile[16] =
{
  0x00,0x00,0x00,0x00,0x00,0x4F,0x06,0x19,
  0x00,0x6F,0x00,0x00,0x00,0x00,0x00,0x00
};

/* End of SPRITE_PLAYER_BULLET.C */
