//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_backgroundtest_H
#define METASPRITE_backgroundtest_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define backgroundtest_TILE_ORIGIN 0
#define backgroundtest_TILE_W 8
#define backgroundtest_TILE_H 8
#define backgroundtest_WIDTH 256
#define backgroundtest_HEIGHT 256
#define backgroundtest_TILE_COUNT 77
#define backgroundtest_PALETTE_COUNT 1
#define backgroundtest_COLORS_PER_PALETTE 4
#define backgroundtest_TOTAL_COLORS 4
#define backgroundtest_MAP_ATTRIBUTES 0

BANKREF_EXTERN(backgroundtest)

extern const palette_color_t backgroundtest_palettes[4];
extern const uint8_t backgroundtest_tiles[1232];

extern const unsigned char backgroundtest_map[1024];

#endif
