//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_fliped_rootpack_testy_H
#define METASPRITE_fliped_rootpack_testy_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define fliped_rootpack_testy_TILE_ORIGIN 0
#define fliped_rootpack_testy_TILE_W 8
#define fliped_rootpack_testy_TILE_H 8
#define fliped_rootpack_testy_WIDTH 256
#define fliped_rootpack_testy_HEIGHT 256
#define fliped_rootpack_testy_TILE_COUNT 77
#define fliped_rootpack_testy_PALETTE_COUNT 1
#define fliped_rootpack_testy_COLORS_PER_PALETTE 4
#define fliped_rootpack_testy_TOTAL_COLORS 4
#define fliped_rootpack_testy_MAP_ATTRIBUTES 0

BANKREF_EXTERN(fliped_rootpack_testy)

extern const palette_color_t fliped_rootpack_testy_palettes[4];
extern const uint8_t fliped_rootpack_testy_tiles[1232];

extern const unsigned char fliped_rootpack_testy_map[1024];

#endif
